language: node_js
node_js:
  - "7"
install:
  - npm install
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
script:
  - npm run lint
  - npm run ci-test
  - npm run build-production
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master
