name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install browser
        run: sudo apt-get install chromium-chromedriver

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run ci-test

      - name: Run webpack
        run: npm run build-production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
