name: run-tests

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install browser
        run: sudo apt-get install chromium-chromedriver

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run ci-test

      - name: Run webpack
        run: npm run build-production
